###
# Copyright (2017) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###
---
- name: Install prometheus/grafana stack withprometheus operator 
  hosts: local
  connection: local
  gather_facts: false

  environment: "{{ env }}"

  tasks:

    - debug: msg="Starting Playbook kube-prometheus operator"

    - name: Creates /tmp/kube-prometheus directory
      file: path=/tmp/kube-prometheus state=directory
      register: file_details

    - name: Creates  operator directory
      file: path=/tmp/kube-prometheus/operator state=directory
      register: file_details


    - name: process operator templates
      template:
        src: "{{ item }}"
        dest: /tmp/kube-prometheus/operator/{{ item | basename | regex_replace('\.j2','') }}
      with_fileglob:
      - "../../templates/kube-prometheus/operator/*.j2"

    - name: Apply yml files to  configure and install prometheus
      shell: |
        kubectl create namespace monitoring
        kubectl apply -f /tmp/kube-prometheus/operator/
      args:
        executable: /usr/bin/bash
      register: ps

    - debug: var=ps.stdout_lines
