###
# Copyright (2017) Hewlett Packard Enterprise Development LP
#
# Licensed under the Apache License, Version 2.0 (the "License");
# You may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###
---
- name: Install prometheus/grafana stack with prometheus operator - prometheus
  hosts: local
  connection: local
  gather_facts: false

  environment: "{{ env }}"

  tasks:

    - debug: msg="Starting Playbook kube-prometheus prometheus"

    - name: Creates /tmp/kube-prometheus directory
      file: path=/tmp/kube-prometheus state=directory
      register: file_details

    - name: Creates  prometheus directory
      file: path=/tmp/kube-prometheus/prometheus state=directory
      register: file_details


    - name: process prometheus templates
      template:
        src: "{{ item }}"
        dest: /tmp/kube-prometheus/prometheus/{{ item | basename | regex_replace('\.j2','') }}
      with_fileglob:
      - "../../templates/kube-prometheus/prometheus/*.j2"


    - name: process prometheus rules file
      copy:
        src: "../../templates/kube-prometheus/prometheus/prometheus-rules.yaml"
        dest: "/tmp/kube-prometheus/prometheus/prometheus-rules.yaml"

    - name: Apply yml files to  configure and install prometheus
      shell: |
        kubectl apply -f /tmp/kube-prometheus/prometheus/
        #kubectl -n monitoring get svc prometheus-k8s
      args:
        executable: /usr/bin/bash
      register: ps

    - debug: var=ps.stdout_lines


    - name: Configure prometheus NodePort
      shell: |
        kubectl -n monitoring patch svc prometheus-k8s --type='json' -p '[{"op":"replace","path":"/spec/type","value":"NodePort"}]'
        kubectl -n monitoring patch svc prometheus-k8s --type='json' -p '[{"op": "add", "path":"/spec/ports/0/nodePort", "value":33090}]'
        kubectl -n monitoring get svc prometheus-k8s
      args:
        executable: /usr/bin/bash
      register: ps

    - debug: var=ps.stdout_lines
